# Generated by Django 3.0 on 2020-01-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnl', '0002_aprendizaje_ejercicio_ejercicior_subtemas_temas_temausuario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='IdTem',
            field=models.IntegerField(max_length=3, null=True),
        ),
    ]
