# Generated by Django 3.0 on 2019-12-28 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pnl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=60)),
                ('Numero', models.IntegerField()),
                ('NSubtemas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreUsuario', models.CharField(max_length=25)),
                ('Nombre', models.CharField(max_length=20)),
                ('ApellidoPaterno', models.CharField(max_length=30)),
                ('ApellidoMaterno', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
                ('FechaNacimiento', models.DateField()),
                ('Nivel', models.IntegerField()),
                ('Progreso', models.IntegerField()),
                ('IdTecnologico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pnl.Tecnologico')),
            ],
        ),
        migrations.CreateModel(
            name='TemaUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Evaluacion', models.FloatField(blank=True, null=True)),
                ('IdTema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pnl.Temas')),
                ('IdUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pnl.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='SubTemas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=60)),
                ('Numero', models.IntegerField()),
                ('NEjercicios', models.IntegerField()),
                ('IdTemas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pnl.Temas')),
            ],
        ),
        migrations.CreateModel(
            name='EjercicioR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(blank=True, max_length=20, null=True)),
                ('NEjer', models.IntegerField()),
                ('Tipo', models.CharField(max_length=20)),
                ('RP1', models.CharField(blank=True, max_length=40, null=True)),
                ('RP2', models.CharField(blank=True, max_length=40, null=True)),
                ('RP3', models.CharField(blank=True, max_length=40, null=True)),
                ('RP4', models.CharField(blank=True, max_length=40, null=True)),
                ('RP5', models.CharField(blank=True, max_length=40, null=True)),
                ('RP6', models.CharField(blank=True, max_length=40, null=True)),
                ('RP7', models.CharField(blank=True, max_length=40, null=True)),
                ('RP8', models.CharField(blank=True, max_length=40, null=True)),
                ('RP9', models.CharField(blank=True, max_length=40, null=True)),
                ('RP10', models.CharField(blank=True, max_length=40, null=True)),
                ('IdSub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pnl.SubTemas')),
                ('IdTem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pnl.Temas')),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('Tipo', models.CharField(max_length=25)),
                ('Evaluacion', models.FloatField(null=True)),
                ('Fecha', models.DateTimeField(blank=True, null=True)),
                ('R1', models.CharField(blank=True, max_length=40, null=True)),
                ('R2', models.CharField(blank=True, max_length=40, null=True)),
                ('R3', models.CharField(blank=True, max_length=40, null=True)),
                ('R4', models.CharField(blank=True, max_length=40, null=True)),
                ('R5', models.CharField(blank=True, max_length=40, null=True)),
                ('R6', models.CharField(blank=True, max_length=40, null=True)),
                ('IdSubtema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pnl.SubTemas')),
                ('IdUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pnl.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Aprendizaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Visual', models.FloatField()),
                ('Auditivo', models.FloatField()),
                ('Kinestesico', models.FloatField()),
                ('CantidadVisuales', models.IntegerField()),
                ('CantidadAuditivos', models.IntegerField()),
                ('CantidadKinestesicos', models.IntegerField()),
                ('IdUsuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pnl.Usuario')),
            ],
        ),
    ]
