# Generated by Django 3.0 on 2020-01-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnl', '0003_ejercicio_idtem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='IdTem',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
    ]
